### ISSUE TITLE
keywords from specific user(s)

### ISSUE THREAD

**Issue by lovebell** [peterdalle/twitterbot#2]
How to set keywords from specific user(s)?

**Comment by peterdalle** [comment]
I haven't tried it myself, but I guess the standard search operators are available. Add `from:username` to your keywords. For example:

```py
def SearchAndRetweet():
	exclude_words = []
	include_words = ["#hashtag", "from:username"]
```
See also [Search Tweets Twitter Documentation](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators) for more search operators.

**Comment by lovebell** [comment]
include_words = ["#hashtag1+from:username1","#hashtag2+from:username2"]

sloved.
