### ISSUE TITLE
FeedUrl

### ISSUE THREAD

**Issue by josepfm** [peterdalle/twitterbot#3]
He's probably not getting it right.

Can you tell me any examples of valid urls?

How to get them, etc...

Thank you.

**Comment by peterdalle** [comment]
`FeedURL` can be any valid URL.

The URL is passed on to [`feedparser.parse()`](https://pythonhosted.org/feedparser/introduction.html) and should just be a feed of some sort (e.g. Atom, RSS) .

http://feeds.bbci.co.uk/news/rss.xml is one example of a feed.
