### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lovebell** [peterdalle/twitterbot#5]
# python ~/twitterbot/twitterbot.py rt
  File "/root/twitterbot/twitterbot.py", line 41
    def compose_message(item: feedparser.FeedParserDict) -> str:
------------------------------^
SyntaxError: invalid syntax

**Comment by peterdalle** [comment]
The app is for Python version 3, not version 2.

Use `python3 ~/twitterbot/twitterbot.py rt` or similar instead.

Note python**3**.

**Comment by lovebell** [comment]
then, it should be,
pip3 install feedparser
pip3 install twython
* * * * * python3 ~/twitterbot/twitterbot.py rss
* * * * * python3 ~/twitterbot/twitterbot.py rt
