### ISSUE TITLE
Error when I change from posting title to description 

### ISSUE THREAD

**Issue by cmutts** [peterdalle/twitterbot#6]
Things work well when posting title. When I change to posting description, I get the error below; Please help 

Traceback (most recent call last):
  File "/root/twitterbot/twitterbot.py", line 227, in <module>
    read_rss_and_tweet(url=Settings.feed_url)
  File "/root/twitterbot/twitterbot.py", line 115, in read_rss_and_tweet
    post_tweet(message=compose_message(item))
  File "/root/twitterbot/twitterbot.py", line 59, in compose_message
    message = shorten_text(description, maxlength=250) + " " + link
NameError: name 'description' is not defined

**Comment by peterdalle** [comment]
I suppose you are talking about the [`compose_message` method](https://github.com/peterdalle/twitterbot/blob/master/twitterbot.py#L42) where `item["description"]` is assigned to nothing (i.e., `_`).

If you replace this:

```py
    title, link, _ = item["title"], item["link"], item["description"]
    message = shorten_text(title, maxlength=250) + " " + link
```
With this:
```py
    title, link, description = item["title"], item["link"], item["description"]
    message = shorten_text(description, maxlength=250) + " " + link
```

It will probably work.

**Comment by cmutts** [comment]
Duplicate of

**Comment by cmutts** [comment]
Yes that's what I was talking about. The compose message method. 
As advised, I have  replaced;

title, link, _ = item["title"], item["link"], item["description"]
    message = shorten_text(title, maxlength=250) + " " + link
With this:

    title, link, description = item["title"], item["link"], item["description"]
    message = shorten_text(description, maxlength=250) + " " + link

My feedurl is this https://rsshub-pohv8mb0m.vercel.app/facebook/page/radiosimba

And yes the error has gone. It's posting now. However, it's only posting the link in my rss to my posts, and not my description.

**Comment by peterdalle** [comment]
That's because there isn't any description contents in the feed.
